TheCarHub/src/TheCarHub/Models/Admin/InventoryViewModel.cs
namespace TheCarHub.Models.Admin
{
    public class InventoryViewModel
    {
        public IReadOnlyList<ICar> Cars { get; }

        public InventoryViewModel(IReadOnlyList<ICar> inventory)
        {
            this.Cars = (inventory ?? new List<ICar>())
                .OrderByDescending(car => car.PurchaseDate)
                .ThenByDescending(car => car.LotDate)
                .ToList()
                .AsReadOnly();
        }
    }
}

TheCarHub/src/TheCarHub/Models/Admin/ManageCarsViewModel.cs
namespace TheCarHub.Models.Admin
{
    public class ManageCarsViewModel
    {
        public IReadOnlyList<ICar> Cars { get; }

        public ManageCarsViewModel(IReadOnlyList<ICar> inventory)
        {
            this.Cars = (inventory ?? new List<ICar>())
                .OrderByDescending(car => car.PurchaseDate)
                .ThenByDescending(car => car.LotDate)
                .ToList()
                .AsReadOnly();
        }
    }
}

TheCarHub/src/TheCarHub/Models/ErrorViewModel.cs
namespace TheCarHub.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TheCarHub/src/TheCarHub/Models/Main/InventoryViewModel.cs
namespace TheCarHub.Models.Main
{
    public class InventoryViewModel
    {
        public IReadOnlyList<ICar> Cars { get; }

        public InventoryViewModel(IReadOnlyList<ICar> inventory, ISystemClock clock)
        {
            this.Cars = (inventory ?? new List<ICar>())
                .OrderByDescending(c => c.SaleDate == null)
                .ThenBy(c => c.LotDate == null || c.LotDate > clock.UtcNow)
                .ToList()
                .AsReadOnly();
        }
    }
}

TheCarHub/src/TheCarHub/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;
using TheCarHub.Models.Admin;

namespace TheCarHub.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly IAdminService _adminService;

        public AdminController(IAdminService adminService)
        {
            this._adminService = adminService ?? throw new ArgumentNullException(nameof(adminService));
        }

        [AllowAnonymous]
        [HttpGet(Routes.Login)]
        public IActionResult Login() => View();

        [AllowAnonymous]
        [HttpPost(Routes.Login)]
        public async Task<IActionResult> Login([FromForm]string username,
            [FromForm]string password, [FromQuery]string? returnUrl)
        {
            var result = await this._adminService.Login(username, password);

            if (!result.Success)
            {
                ModelState.AddModelError(string.Empty, result.FailureUserMessage!);

                return View();
            }

            return LocalRedirect(this.Url.IsLocalUrl(returnUrl)
                ? returnUrl : Routes.ManageCars);
        }

        [HttpPost(Routes.Logout)]
        public async Task<IActionResult> Logout()
        {
            await this._adminService.Logout();

            return Redirect(MainController.Routes.Inventory);
        }

        [HttpGet(Routes.ManageCars)]
        public async Task<IActionResult> ManageCars()
        {
            var inventory = await this._adminService.GetInventory();

            return View(new ManageCarsViewModel(inventory));
        }

        [HttpGet(Routes.CreateCar)]
        public IActionResult CreateCar() => View(new CarPoco());

        [HttpPost(Routes.CreateCar)]
        public async Task<IActionResult> CreateCar([FromForm]CarPoco car)
        {
            if (!ModelState.IsValid)
                return View(car);

            await this._adminService.CreateCar(car);

            return Redirect(Routes.ManageCars);
        }

        [HttpGet(Routes.UpdateCar)]
        public async Task<IActionResult> UpdateCar([FromRoute]Guid id)
        {
            var car = await this._adminService.GetCar(id);

            return car != null
                ? View(new CarPoco(car))
                : Redirect(Routes.ManageCars);
        }

        [HttpPost(Routes.UpdateCar)]
        public async Task<IActionResult> UpdateCar([FromRoute]Guid id,
            [FromForm]CarPoco car)
        {
            if (!ModelState.IsValid)
                return View(car);

            car.Id = id;

            await this._adminService.UpdateCar(car);

            return Redirect(Routes.ManageCars);
        }

        [HttpGet(Routes.UpdateCar_Pictures)]
        public async Task<IActionResult> UpdateCar_Pictures(
            [FromRoute]Guid id)
        {
            var car = await this._adminService.GetCar(id);

            return car != null
                ? View(new CarPoco(car))
                : Redirect(Routes.ManageCars);
        }

        [HttpPost(Routes.UpdateCar_PicturesAdd)]
        public async Task<IActionResult> UpdateCar_PicturesAdd(
            [FromRoute]Guid id, [FromForm]IFormFile picture)
        {
            if (picture is null)
            {
                return RedirectToAction(nameof(UpdateCar_Pictures), new { id });
            }

            await this._adminService.UpdateCar_AddPicture(id, picture);

            return RedirectToAction(nameof(UpdateCar_Pictures), new { id });
        }

        [HttpPost(Routes.UpdateCar_PicturesDelete)]
        public async Task<IActionResult> UpdateCar_PicturesDelete(
            [FromRoute] Guid id, [FromForm]string pictureUri)
        {
            await this._adminService.UpdateCar_DeletePicture(id, pictureUri);

            return RedirectToAction(nameof(UpdateCar_Pictures), new { id });
        }

        [HttpGet(Routes.DeleteCarConfirm)]
        public async Task<IActionResult> DeleteCarConfirm([FromRoute]Guid id)
        {
            var car = await this._adminService.GetCar(id);

            return car != null ? View(car) : Redirect(Routes.ManageCars);
        }

        [HttpPost(Routes.DeleteCar)]
        public async Task<IActionResult> DeleteCar([FromForm]Guid id)
        {
            await this._adminService.DeleteCar(id);

            return Redirect(Routes.ManageCars);
        }

        public static class Routes
        {
            public const string Login = "/admin/login";
            public const string Logout = "/admin/logout";
            public const string ManageCars = "/admin";
            public const string CreateCar = "/admin/add";
            public const string UpdateCar = "/admin/update/{id}";
            public const string UpdateCar_Pictures = "/admin/update/{id}/pictures";
            public const string UpdateCar_PicturesAdd = "/admin/update/{id}/pictures/add";
            public const string UpdateCar_PicturesDelete = "/admin/update/{id}/pictures/delete";
            public const string DeleteCarConfirm = "/admin/delete/{id}";
            public const string DeleteCar = "/admin/delete";
        }
    }
}

TheCarHub/src/TheCarHub/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TheCarHub.Models;
using TheCarHub.Models.Main;

namespace TheCarHub.Controllers
{
    public class MainController : Controller
    {
        private readonly IDealershipService _dealershipService;

        public MainController(IDealershipService dealershipService)
        {
            this._dealershipService = dealershipService ?? throw new ArgumentNullException(nameof(dealershipService));
        }

        [HttpGet(Routes.Inventory)]
        public async Task<IActionResult> Inventory([FromServices]ISystemClock clock)
        {
            var inventory = await this._dealershipService.GetInventory();

            return View(new InventoryViewModel(inventory, clock));
        }

        [HttpGet(Routes.Error)]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public static class Routes
        {
            public const string Inventory = "/";
            public const string Error = "/error";
        }
    }
}

TheCarHub/src/TheCarHub/Views/Admin/CreateCar.cshtml
@model TheCarHub.CarPoco
@inject TheCarHub.ISystemClock Clock
@{
    ViewBag.Title = "Create Car";
}

<div class="text-center">
    <h1 class="display-4">@ViewBag.Title</h1>
    <p>Add a new car purchase to the dealership's inventory</p>
</div>
<form method="post" enctype="multipart/form-data" asp-antiforgery="true">
    <input type="hidden" name="@nameof(Model.Id)" value="@Model!.Id" />
    <p>
        <label asp-for="Vin">VIN:</label><br />
        <input asp-for="Vin" /><br />
        <span asp-validation-for="Vin"></span>
    </p>
    <p>
        <label asp-for="Year">Year:</label><br />
        <select asp-for="Year" required>
            @for (var year = 1990; year <= Clock.UtcNow.Year + 1; year++)
            {
                <option value="@year">@year</option>
            }
        </select><br />
        <span asp-validation-for="Year"></span>
    </p>
    <p>
        <label asp-for="Make">Make*:</label><br />
        <input asp-for="Make" required /><br />
        <span asp-validation-for="Make"></span>
    </p>
    <p>
        <label asp-for="Model">Model*:</label><br />
        <input asp-for="Model" required /><br />
        <span asp-validation-for="Model"></span>
    </p>
    <p>
        <label asp-for="Trim">Trim*:</label><br />
        <input asp-for="Trim" required /><br />
        <span asp-validation-for="Trim"></span>
    </p>
    <p>
        <label asp-for="PurchaseDate">Purchase Date:</label><br />
        <input asp-for="PurchaseDate" class="datepicker" value="@Model.PurchaseDate.ToString("yyyy/MM/dd")" required /><br />
        <span asp-validation-for="PurchaseDate"></span>
    </p>
    <p>
        <label asp-for="PurchasePrice">Purchase Price:</label><br />
        <input asp-for="PurchasePrice" required /><br />
        <span asp-validation-for="PurchasePrice"></span>
    </p>
    <p>
        <label asp-for="Repairs">Repairs:</label><br />
        <input asp-for="Repairs" /><br />
        <span asp-validation-for="Repairs"></span>
    </p>
    <p>
        <label asp-for="RepairCost">Repair Cost:</label><br />
        <input asp-for="RepairCost" required /><br />
        <span asp-validation-for="RepairCost"></span>
    </p>
    <p>
        <label asp-for="LotDate">Lot Date:</label><br />
        <input asp-for="LotDate" class="datepicker" value="@Model.LotDate?.ToString("yyyy/MM/dd")" /><br />
        <span asp-validation-for="LotDate"></span>
    </p>
    <p>
        <label asp-for="SaleDate">Sale Date:</label><br />
        <input asp-for="SaleDate" class="datepicker" value="@Model.SaleDate?.ToString("yyyy/MM/dd")" /><br />
        <span asp-validation-for="SaleDate"></span>
    </p>
    <p>
        <label asp-for="Profit">Profit:</label><br />
        <input asp-for="Profit" required /><br />
        <span asp-validation-for="Profit"></span>
    </p>
    <div asp-validation-summary="ModelOnly"></div>
    <input type="submit" value="Add Car" />
</form>

@section Styles {
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-datepicker3.min.css" />
}

@section Scripts {
<script src="~/lib/bootstrap/dist/js/bootstrap-datepicker.min.js"></script>
}

TheCarHub/src/TheCarHub/Views/Admin/DeleteCarConfirm.cshtml
@model TheCarHub.ICar
@{
    ViewBag.Title = "Confirm Delete";
}

<div class="text-center">
    <h1 class="display-4">@ViewBag.Title</h1>
    <p>Are you sure you want to permanently delete this car?</p>
</div>
<form method="post" asp-controller="Admin" asp-action="DeleteCar" asp-antiforgery="true">
    <input type="hidden" name="@nameof(Model.Id)" value="@Model!.Id" />
    @if (Model.PictureUris.Any())
    {
        <p>
            Picture:<br />
            <img src="@Model.PictureUris.First()" alt="@Model.ToString()" />
        </p>
    }
    @if (!string.IsNullOrWhiteSpace(Model.Vin))
    {
        <p>
            <label asp-for="Vin">VIN:</label><br />
            <input asp-for="Vin" disabled />
        </p>
    }
    <p>
        <label asp-for="Year">Year:</label><br />
        <input asp-for="Year" disabled />
    </p>
    <p>
        <label asp-for="Make">Make:</label><br />
        <input asp-for="Make" disabled />
    </p>
    <p>
        <label asp-for="Model">Model:</label><br />
        <input asp-for="Model" disabled />
    </p>
    <p>
        <label asp-for="Trim">Trim:</label><br />
        <input asp-for="Trim" disabled />
    </p>
    <p>
        <label asp-for="PurchaseDate">Purchase Date:</label><br />
        <input asp-for="PurchaseDate" disabled />
    </p>
    <p>
        <label asp-for="PurchasePrice">Purchase Price:</label><br />
        <input asp-for="PurchasePrice" disabled />
    </p>
    @if (!string.IsNullOrWhiteSpace(Model.Repairs))
    {
        <p>
            <label asp-for="Repairs">Repairs:</label><br />
            <input asp-for="Repairs" disabled />
        </p>
    }
    <p>
        <label asp-for="RepairCost">Repair Cost:</label><br />
        <input asp-for="RepairCost" disabled />
    </p>
    @if (Model.LotDate.HasValue)
    {
        <p>
            <label asp-for="LotDate">Lot Date:</label><br />
            <input asp-for="LotDate" disabled />
        </p>
    }
    @if (Model.SaleDate.HasValue)
    {
        <p>
            <label asp-for="SaleDate">Sale Date:</label><br />
            <input asp-for="SaleDate" disabled />
        </p>
    }
    <p>
        <label asp-for="SellingPrice">Selling Price:</label><br />
        <input asp-for="SellingPrice" disabled />
    </p>
    <input type="submit" value="Delete Car" />
</form>

TheCarHub/src/TheCarHub/Views/Admin/DeleteConfirm.cshtml
@model TheCarHub.ICar
@{
    ViewBag.Title = "Confirm Delete";
}

<div class="text-center">
    <h1 class="display-4">@ViewBag.Title</h1>
    <p>Are you sure you want to permanently delete this car?</p>
</div>
<form method="post" asp-controller="Admin" asp-action="Delete" asp-antiforgery="true">
    <input type="hidden" name="@nameof(Model.Id)" value="@Model!.Id" />
    @if (!string.IsNullOrWhiteSpace(Model.Vin))
    {
        <p>
            <label asp-for="Vin">VIN:</label><br />
            <input asp-for="Vin" disabled />
        </p>
    }
    <p>
        <label asp-for="Year">Year:</label><br />
        <input asp-for="Year" disabled />
    </p>
    <p>
        <label asp-for="Make">Make:</label><br />
        <input asp-for="Make" disabled />
    </p>
    <p>
        <label asp-for="Model">Model:</label><br />
        <input asp-for="Model" disabled />
    </p>
    <p>
        <label asp-for="Trim">Trim:</label><br />
        <input asp-for="Trim" disabled />
    </p>
    <p>
        <label asp-for="PurchaseDate">Purchase Date:</label><br />
        <input asp-for="PurchaseDate" disabled />
    </p>
    <p>
        <label asp-for="PurchasePrice">Purchase Price:</label><br />
        <input asp-for="PurchasePrice" disabled />
    </p>
    @if (!string.IsNullOrWhiteSpace(Model.Repairs))
    {
        <p>
            <label asp-for="Repairs">Repairs:</label><br />
            <input asp-for="Repairs" disabled />
        </p>
    }
    <p>
        <label asp-for="RepairCost">Repair Cost:</label><br />
        <input asp-for="RepairCost" disabled />
    </p>
    @if (Model.LotDate.HasValue)
    {
        <p>
            <label asp-for="LotDate">Lot Date:</label><br />
            <input asp-for="LotDate" disabled />
        </p>
    }
    @if (Model.SaleDate.HasValue)
    {
        <p>
            <label asp-for="SaleDate">Sale Date:</label><br />
            <input asp-for="SaleDate" disabled />
        </p>
    }
    <p>
        <label asp-for="SellingPrice">Selling Price:</label><br />
        <input asp-for="SellingPrice" disabled />
    </p>
    <input type="submit" value="Delete Car" />
</form>

TheCarHub/src/TheCarHub/Views/Admin/Inventory.cshtml
@model TheCarHub.Models.Admin.InventoryViewModel
@{
    ViewBag.Title = "Inventory";
}

<div class="text-center">
    <h1 class="display-4">Admin Inventory</h1>
    <p>Use this portal to create and update the cars in your dealership</p>
</div>
<table>
    <thead>
        <tr>
            <td></td>
            <td>VIN</td>
            <td>Year</td>
            <td>Make</td>
            <td>Model</td>
            <td>Trim</td>
            <td>Purchase Date</td>
            <td>Purchase Price</td>
            <td>Repairs</td>
            <td>Repair Cost</td>
            <td>Lot Date</td>
            <td>Selling Price</td>
            <td>Sale Date</td>
            <td></td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @foreach (var car in Model!.Cars)
        {
            <tr>
                <td>
                    @if (car.PictureUri is not null)
                    {
                        <img src="@car.PictureUri" alt="@car.ToString()" />
                    }
                    else
                    {
                        <img src="~/images/car-placeholder.jpg" alt="@car.ToString()" />
                    }
                </td>
                <td>@car.Vin</td>
                <td>@car.Year</td>
                <td>@car.Make</td>
                <td>@car.Model</td>
                <td>@car.Trim</td>
                <td>@car.PurchaseDate.ToString("MMM d, yyyy")</td>
                <td>@car.PurchasePrice.ToString("C")</td>
                <td>@car.Repairs</td>
                <td>@car.RepairCost.ToString("C")</td>
                <td>@car.LotDate?.ToString("MMM d, yyyy")</td>
                <td>@car.SellingPrice.ToString("C")</td>
                <td>@car.SaleDate?.ToString("MMM d, yyyy")</td>
                <td>
                    <a href="~/admin/update/@car.Id">Update</a>
                </td>
                <td>
                    <a href="~/admin/delete/@car.Id">Delete</a>
                </td>
            </tr>
        }

        @if (!Model.Cars.Any())
        {
            <tr>
                <td colspan="10">There are currently no cars in your inventory.</td>
            </tr>
        }
    </tbody>
</table>

TheCarHub/src/TheCarHub/Views/Admin/Login.cshtml
@{
    ViewBag.Title = "Admin Login";
}

<div class="text-center">
    <h1 class="display-4">@ViewBag.Title</h1>
    <p>Login to manage the dealership's inventory</p>
</div>
<form method="post" asp-antiforgery="true">
    <p>
        <label for="username">Username:</label><br />
        <input type="text" name="username" required autofocus />
    </p>
    <p>
        <label for="password">Password:</label><br />
        <input type="password" name="password" required />
    </p>
    <div asp-validation-summary="All" class="alert-danger"></div>
    <input type="submit" value="Login" />
</form>

TheCarHub/src/TheCarHub/Views/Admin/ManageCars.cshtml
@model TheCarHub.Models.Admin.ManageCarsViewModel
@{
    ViewBag.Title = "Manage Cars";
}

<div class="text-center">
    <h1 class="display-4">Manage Cars</h1>
    <p>Use this portal to create and update the cars in your dealership</p>
</div>
<table>
    <thead>
        <tr>
            <td></td>
            <td>VIN</td>
            <td>Year</td>
            <td>Make</td>
            <td>Model</td>
            <td>Trim</td>
            <td>Purchase Date</td>
            <td>Purchase Price</td>
            <td>Repairs</td>
            <td>Repair Cost</td>
            <td>Lot Date</td>
            <td>Selling Price</td>
            <td>Sale Date</td>
            <td></td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @foreach (var car in Model!.Cars)
        {
            <tr>
                <td class="picture">
                    @if (car.PictureUris.Any())
                    {
                        <img src="@car.PictureUris.First()" alt="@car.ToString()" />
                    }
                    else
                    {
                        <img src="~/images/car-placeholder.jpg" alt="@car.ToString()" />
                    }
                    <br />
                    <a href="~/admin/update/@car.Id/pictures">Manage Pictures</a>
                </td>
                <td>@car.Vin</td>
                <td>@car.Year</td>
                <td>@car.Make</td>
                <td>@car.Model</td>
                <td>@car.Trim</td>
                <td>@car.PurchaseDate.ToString("MMM d, yyyy")</td>
                <td>@car.PurchasePrice.ToString("C")</td>
                <td>@car.Repairs</td>
                <td>@car.RepairCost.ToString("C")</td>
                <td>@car.LotDate?.ToString("MMM d, yyyy")</td>
                <td>@car.SellingPrice.ToString("C")</td>
                <td>@car.SaleDate?.ToString("MMM d, yyyy")</td>
                <td>
                    <a href="~/admin/update/@car.Id">Update</a>
                </td>
                <td>
                    <a href="~/admin/delete/@car.Id">Delete</a>
                </td>
            </tr>
        }

        @if (!Model.Cars.Any())
        {
            <tr>
                <td colspan="10">There are currently no cars in your inventory.</td>
            </tr>
        }
    </tbody>
</table>

TheCarHub/src/TheCarHub/Views/Admin/UpdateCar_Pictures.cshtml
@model TheCarHub.CarPoco
@{
    ViewBag.Title = "Update Car Pictures";
}

<div class="text-center">
    <h1 class="display-4">@ViewBag.Title</h1>
    <p>Update the pictures associated with this car</p>
</div>
<div>
    <h2>@Model!.ToString()</h2>
    @if (Model.PictureUris.Any())
    {
        foreach (var pictureUri in Model.PictureUris)
        {
            <form class="delete-picture" method="post" asp-controller="Admin"
                asp-action="UpdateCar_PicturesDelete"
                asp-route-id="@Model.Id"
                asp-antiforgery="true">
                <p>
                    <img src="@pictureUri" />
                    <input type="hidden" name="pictureUri" value="@pictureUri" />
                    <button>Delete</button>
                </p>
            </form>
        }
    }
    else
    {
        <p>
            This car currently has no pictures.
        </p>
    }

    <div>
        <form method="post" enctype="multipart/form-data"
              asp-controller="Admin" asp-action="UpdateCar_PicturesAdd"
              asp-antiforgery="true" asp-route-id="@Model.Id">
            <p>
                <label for="Picture">Add a Picture:</label><br />
                <input type="file" id="Picture" name="Picture" accept="image/png, image/jpeg" />
            </p>
            <p>
                <button>Upload Picture</button>
            </p>
        </form>
    </div>
</div>

TheCarHub/src/TheCarHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title &ndash; The Car Hub</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TheCarHub.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">The Car Hub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Admin" asp-action="ManageCars">Manage Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Admin" asp-action="CreateCar">Add a Car</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Main" asp-action="Inventory">Public Inventory</a>
                            </li>
                            <li class="nav-item">
                                <form method="post" asp-controller="Admin" asp-action="Logout" asp-antiforgery="true">
                                    <button id="logout-button">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Main" asp-action="Inventory">Browse our Inventory</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 The Car Hub &ndash;
            <a asp-controller="Admin" asp-action="ManageCars">Admin</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>